version: 2
updates:
#- package-ecosystem: npm
#  directory: "/"
#  schedule:
#    interval: weekly
#    time: "04:00"
#    timezone: Europe/Paris
#  open-pull-requests-limit: 10
#  ignore:
#  - dependency-name: bootstrap for example
#    versions:
#    - "> 4 alpha etc. "
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
#  reviewers:
#  - nicosomb
#  labels:
#  - Ready for review
#  ignore:
# list of dependencies to ignore
